Failsafe logging
oat-sa/lib-dbal-spanner pull request #3
Opened 2019-10-15 14:13 UTC by boajer

2019-10-16 13:09 UTC, julien-sebire requested changes
Why throw exceptions instead of return false?

2019-10-16 13:30 UTC, boajer commented
@julien-sebire I've did that on purpose, in the same way how it works in similar classes, like https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOStatement.php#L123 , https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php#L143, or I believe any other implementations of https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/Statement.php#L13

Additionally we shouldn't be in the situation without any traces of unexpected circumstances or errors, that is may be possible without properly injected logger ( And I believe to inject it there are quite a lot of  other changes needed  in the core)

2019-10-17 08:18 UTC, mike-ionut-mihai-sandu-tao approved these changes

2019-10-17 08:24 UTC, julien-sebire approved these changes
All good for me.

2019-10-17 08:25 UTC, merged